# Generated by Django 4.1.3 on 2022-11-26 06:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Picture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('picture', models.ImageField(upload_to='', verbose_name='Picture')),
                ('description', models.CharField(max_length=200, verbose_name='description')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pictures', to=settings.AUTH_USER_MODEL, verbose_name='author')),
                ('favored_by', models.ManyToManyField(blank=True, related_name='favorite_pictures', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
