# Generated by Django 4.1.3 on 2022-11-26 09:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0002_alter_picture_managers'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='picture',
            managers=[
            ],
        ),
    ]
